# Generated by Django 4.1.7 on 2023-04-26 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('knox', '0008_remove_authtoken_salt'),
        ('profiles', '0002_device'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='token',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='knox.authtoken'),
        ),
    ]
